using System;

namespace DirectN
{
    [Flags]
    public enum MF_MEDIATYPE_EQUAL_FLAGS
    {
        MF_MEDIATYPE_EQUAL_MAJOR_TYPES = Constants.MF_MEDIATYPE_EQUAL_MAJOR_TYPES,
        MF_MEDIATYPE_EQUAL_FORMAT_TYPES = Constants.MF_MEDIATYPE_EQUAL_FORMAT_TYPES,
        MF_MEDIATYPE_EQUAL_FORMAT_DATA = Constants.MF_MEDIATYPE_EQUAL_FORMAT_DATA,
        MF_MEDIATYPE_EQUAL_FORMAT_USER_DATA = Constants.MF_MEDIATYPE_EQUAL_FORMAT_USER_DATA,
    }
}
