namespace DirectN
{
    public enum D2D1_GEOMETRY_SIMPLIFICATION_OPTION
    {
        D2D1_GEOMETRY_SIMPLIFICATION_OPTION_CUBICS_AND_LINES = 0,
        D2D1_GEOMETRY_SIMPLIFICATION_OPTION_LINES = 1,
    }
}
