namespace DirectN
{
    public enum DWRITE_TEXT_ALIGNMENT
    {
        DWRITE_TEXT_ALIGNMENT_LEADING,
        DWRITE_TEXT_ALIGNMENT_TRAILING,
        DWRITE_TEXT_ALIGNMENT_CENTER,
        DWRITE_TEXT_ALIGNMENT_JUSTIFIED
    }
}
