namespace DirectN
{
    public enum DWRITE_PARAGRAPH_ALIGNMENT
    {
        DWRITE_PARAGRAPH_ALIGNMENT_NEAR,
        DWRITE_PARAGRAPH_ALIGNMENT_FAR,
        DWRITE_PARAGRAPH_ALIGNMENT_CENTER
    }
}
