namespace DirectN
{
    public enum MF_ATTRIBUTE_TYPE
    {
        MF_ATTRIBUTE_UINT32 = VARTYPE.VT_UI4,
        MF_ATTRIBUTE_UINT64 = VARTYPE.VT_UI8,
        MF_ATTRIBUTE_DOUBLE = VARTYPE.VT_R8,
        MF_ATTRIBUTE_GUID = VARTYPE.VT_CLSID,
        MF_ATTRIBUTE_STRING = VARTYPE.VT_LPWSTR,
        MF_ATTRIBUTE_BLOB = VARTYPE.VT_VECTOR | VARTYPE.VT_UI1,
        MF_ATTRIBUTE_IUNKNOWN = VARTYPE.VT_UNKNOWN
    }
}
